SELECT V.VEN_COD,
	V.VEN_DATA_HORA,
	V.VEN_QTDE_PROD,
	V.VEN_SUBTOTAL,
	V.VEN_DESCONTO,
	V.VEN_TOTAL,
	V.VEN_FORMA_PGTO,
	VP.VP_QTD_ITEM,
	VP.VP_TOTAL_ITEM,
	PD.PROD_CODIGO,
	PD.PROD_PRECO,
	MA.MARCA_SIGLA,
	FU.FUNC_NOME,
	CLI.CLI_NOME
FROM TB_VENDA V
INNER JOIN TB_VENDA_PRODUTO VP ON V.VEN_ID = VP.VEN_ID
INNER JOIN TB_PRODUTO PD ON VP.PROD_ID = PD.PROD_ID
INNER JOIN TB_MARCA MA ON PD.MARCA_ID = MA.MARCA_ID
INNER JOIN TB_FUNCIONARIO FU ON V.FUNC_ID = FU.FUNC_ID
INNER JOIN TB_CLIENTE CLI ON V.CLI_ID = CLI.CLI_ID