/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.apsoo.view;

import javax.swing.*;
import br.com.apsoo.dto.Controladora;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;


public class Interface extends javax.swing.JFrame {
   
    private Controladora controladora;
    private DefaultTableModel model;
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        
        this.controladora = new Controladora();
        this.controladora.setTimerDataHora(jLabel38, jLabel42);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painel_base = new javax.swing.JPanel();
        jPanelInicial = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanelMenuVenda = new javax.swing.JPanel();
        btnRealizarVenda = new javax.swing.JButton();
        btnRealizarOrçamento = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanelVenda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputNumOrcamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumVenda = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtQtdItens = new javax.swing.JLabel();
        inputCPFCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JLabel();
        btnCancelarVenda = new javax.swing.JButton();
        btnConfirmarVenda = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtNomeVendedor = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCodVendedor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanelOrcamento = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtNumOrc = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdutosOrc = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        btnAddItemOrc = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtSubtotalOrc = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtQtdItensOrc = new javax.swing.JLabel();
        inputCPFClienteOrc = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNomeClienteOrc = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtTotalOrc = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtDescontoOrc = new javax.swing.JLabel();
        btnCancelarOrc = new javax.swing.JButton();
        btnConfirmarOrc = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtNomeVendOrc = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtCodVendOrc = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelSelecaoProduto = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProdutosSelecao = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSpinnerQtdProduto = new javax.swing.JSpinner();
        btnCancelarSelecao = new javax.swing.JButton();
        btnConfirmarSelecao = new javax.swing.JButton();
        jPanelPagamento = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRBDinheiro = new javax.swing.JRadioButton();
        jRBCredito = new javax.swing.JRadioButton();
        jRBDebito = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        inputPgtoDin = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtTotalPgto = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtTrocoPgto = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        jSpinnerPgtoCartao = new javax.swing.JSpinner();
        btnCancelarPgto = new javax.swing.JButton();
        btnConfirmarPgto = new javax.swing.JButton();
        txtParcela = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        painel_lateral = new javax.swing.JPanel();
        btnEstoque = new javax.swing.JButton();
        btnVenda = new javax.swing.JButton();
        btnRetirada = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venda de Eletrônicos");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1200, 900));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Principal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel_base.setBackground(new java.awt.Color(204, 204, 255));
        painel_base.setLayout(new java.awt.CardLayout());

        jLabel38.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel38.setText("01/01/99");

        jLabel42.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel42.setText("12:12:12");

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicialLayout.createSequentialGroup()
                .addContainerGap(597, Short.MAX_VALUE)
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel42))
                .addGap(37, 37, 37))
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addGap(504, 504, 504))
        );

        painel_base.add(jPanelInicial, "card5");

        btnRealizarVenda.setText("Venda");
        btnRealizarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRealizarVendaMouseClicked(evt);
            }
        });

        btnRealizarOrçamento.setText("Orçamento");
        btnRealizarOrçamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRealizarOrçamentoMouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel36.setText("01/01/99");

        jLabel37.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel37.setText("12:12:12");

        javax.swing.GroupLayout jPanelMenuVendaLayout = new javax.swing.GroupLayout(jPanelMenuVenda);
        jPanelMenuVenda.setLayout(jPanelMenuVendaLayout);
        jPanelMenuVendaLayout.setHorizontalGroup(
            jPanelMenuVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuVendaLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnRealizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnRealizarOrçamento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuVendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMenuVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36))
                .addGap(34, 34, 34))
        );
        jPanelMenuVendaLayout.setVerticalGroup(
            jPanelMenuVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuVendaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addGap(105, 105, 105)
                .addGroup(jPanelMenuVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRealizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRealizarOrçamento, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        painel_base.add(jPanelMenuVenda, "card2");

        jPanelVenda.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Nº Orçamento");

        inputNumOrcamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputNumOrcamentoKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Nº Venda");

        txtNumVenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNumVenda.setText("0000000");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("01/01/99");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("12:12:12");

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código Produto", "Descrição", "Marca", "Preço Unitário", "Quantidade", "Total Produto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Itens da venda");

        btnAddItem.setText("Adcionar Item");
        btnAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddItemMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Subtotal");

        txtSubtotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSubtotal.setText("R$ 0,00");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Itens");

        txtQtdItens.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtQtdItens.setText("000");

        inputCPFCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputCPFClienteKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("CPF do Cliente");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("CPF do Cliente");

        txtNomeCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNomeCliente.setText("INSIRA O CPF DO CLIENTE");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel11.setText("Total da Compra");

        txtTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtTotal.setText("R$ 0,00");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel12.setText("Desconto");

        txtDesconto.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        txtDesconto.setText("R$ 0,00");

        btnCancelarVenda.setText("CANCELAR");
        btnCancelarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarVendaMouseClicked(evt);
            }
        });

        btnConfirmarVenda.setText("CONFIRMAR");
        btnConfirmarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarVendaMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Vendedor:");

        txtNomeVendedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNomeVendedor.setText("NOME DO VENDEDOR");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Código Vendedor:");

        txtCodVendedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCodVendedor.setText("0000000");

        javax.swing.GroupLayout jPanelVendaLayout = new javax.swing.GroupLayout(jPanelVenda);
        jPanelVenda.setLayout(jPanelVendaLayout);
        jPanelVendaLayout.setHorizontalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                        .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVendaLayout.createSequentialGroup()
                                .addComponent(btnAddItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdItens)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelVendaLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputNumOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendaLayout.createSequentialGroup()
                        .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelVendaLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(159, 159, 159)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodVendedor)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendaLayout.createSequentialGroup()
                                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                                        .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelVendaLayout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanelVendaLayout.createSequentialGroup()
                                                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                                                        .addGap(31, 31, 31)
                                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCancelarVenda)
                                                .addGap(40, 40, 40)))
                                        .addComponent(btnConfirmarVenda))
                                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                                        .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(inputCPFCliente)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jSeparator4))
                                .addGap(27, 27, 27)))
                        .addContainerGap())
                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelVendaLayout.setVerticalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputNumOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumVenda)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(jLabel7)
                    .addComponent(txtSubtotal)
                    .addComponent(jLabel9)
                    .addComponent(txtQtdItens))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(txtCodVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeVendedor)
                .addGap(12, 12, 12)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendaLayout.createSequentialGroup()
                        .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendaLayout.createSequentialGroup()
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendaLayout.createSequentialGroup()
                                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtDesconto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConfirmarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_base.add(jPanelVenda, "card3");

        jPanelOrcamento.setBackground(new java.awt.Color(255, 204, 204));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Nº Orçamento");

        txtNumOrc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNumOrc.setText("0000000");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setText("01/01/99");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setText("12:12:12");

        jTableProdutosOrc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código Produto", "Descrição", "Marca", "Preço Unitário", "Quantidade", "Total Produto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableProdutosOrc);

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setText("Itens do Orçamento");

        btnAddItemOrc.setText("Adcionar Item");
        btnAddItemOrc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddItemOrcMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel20.setText("Subtotal");

        txtSubtotalOrc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSubtotalOrc.setText("R$ 0,00");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setText("Itens");

        txtQtdItensOrc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtQtdItensOrc.setText("000");

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel22.setText("CPF do Cliente");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel23.setText("CPF do Cliente");

        txtNomeClienteOrc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNomeClienteOrc.setText("INSIRA O CPF DO CLIENTE");

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel24.setText("Total do Orçamento");

        txtTotalOrc.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtTotalOrc.setText("R$ 0,00");

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel25.setText("Desconto");

        txtDescontoOrc.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        txtDescontoOrc.setText("R$ 0,00");

        btnCancelarOrc.setText("CANCELAR");
        btnCancelarOrc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarOrcMouseClicked(evt);
            }
        });

        btnConfirmarOrc.setText("CONFIRMAR");
        btnConfirmarOrc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarOrcMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel26.setText("Vendedor:");

        txtNomeVendOrc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNomeVendOrc.setText("NOME DO VENDEDOR");

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel27.setText("Código Vendedor:");

        txtCodVendOrc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCodVendOrc.setText("0000000");

        javax.swing.GroupLayout jPanelOrcamentoLayout = new javax.swing.GroupLayout(jPanelOrcamento);
        jPanelOrcamento.setLayout(jPanelOrcamentoLayout);
        jPanelOrcamentoLayout.setHorizontalGroup(
            jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrcamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrcamentoLayout.createSequentialGroup()
                        .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelOrcamentoLayout.createSequentialGroup()
                                .addComponent(btnAddItemOrc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(txtQtdItensOrc)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txtSubtotalOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelOrcamentoLayout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumOrc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrcamentoLayout.createSequentialGroup()
                        .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeVendOrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrcamentoLayout.createSequentialGroup()
                                .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelOrcamentoLayout.createSequentialGroup()
                                        .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel25))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                        .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTotalOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDescontoOrc))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCancelarOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnConfirmarOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelOrcamentoLayout.createSequentialGroup()
                                        .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(inputCPFClienteOrc)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNomeClienteOrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(27, 27, 27))
                            .addGroup(jPanelOrcamentoLayout.createSequentialGroup()
                                .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelOrcamentoLayout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(159, 159, 159)
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCodVendOrc))
                                    .addComponent(jLabel19))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanelOrcamentoLayout.setVerticalGroup(
            jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrcamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNumOrc)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(17, 17, 17)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItemOrc)
                    .addComponent(jLabel20)
                    .addComponent(txtSubtotalOrc)
                    .addComponent(jLabel21)
                    .addComponent(txtQtdItensOrc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(txtCodVendOrc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeVendOrc)
                .addGap(18, 18, 18)
                .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCPFClienteOrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeClienteOrc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtDescontoOrc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtTotalOrc)
                    .addComponent(btnCancelarOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        painel_base.add(jPanelOrcamento, "card4");

        jPanelSelecaoProduto.setBackground(new java.awt.Color(153, 153, 153));

        jTableProdutosSelecao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código Produto", "Descrição", "Marca", "Preço Unitário", "Quantidade Estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableProdutosSelecao);

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel28.setText("Mostrando Somente Itens em Estoque");

        jLabel29.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        jLabel29.setText("Catálogo de Produtos");

        jLabel30.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel30.setText("Item(s)");

        jLabel31.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel31.setText("Selecione a Quantidade Desejada:");

        jSpinnerQtdProduto.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        btnCancelarSelecao.setText("CANCELAR");
        btnCancelarSelecao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarSelecaoMouseClicked(evt);
            }
        });

        btnConfirmarSelecao.setText("CONFIRMAR");
        btnConfirmarSelecao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarSelecaoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSelecaoProdutoLayout = new javax.swing.GroupLayout(jPanelSelecaoProduto);
        jPanelSelecaoProduto.setLayout(jPanelSelecaoProdutoLayout);
        jPanelSelecaoProdutoLayout.setHorizontalGroup(
            jPanelSelecaoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelecaoProdutoLayout.createSequentialGroup()
                .addGroup(jPanelSelecaoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelSelecaoProdutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSpinnerQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addGap(202, 202, 202)
                        .addComponent(btnCancelarSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmarSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSelecaoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelSelecaoProdutoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel28))
                        .addGroup(jPanelSelecaoProdutoLayout.createSequentialGroup()
                            .addGap(199, 199, 199)
                            .addComponent(jLabel29))
                        .addGroup(jPanelSelecaoProdutoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelSelecaoProdutoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanelSelecaoProdutoLayout.setVerticalGroup(
            jPanelSelecaoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSelecaoProdutoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel29)
                .addGap(32, 32, 32)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addGap(2, 2, 2)
                .addGroup(jPanelSelecaoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSelecaoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelarSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConfirmarSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSelecaoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        painel_base.add(jPanelSelecaoProduto, "card6");

        jPanelPagamento.setBackground(new java.awt.Color(255, 255, 193));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel3.setText("Pagamento da Compra");

        jRBDinheiro.setText("Pagamento em dinheiro");
        jRBDinheiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBDinheiroMouseClicked(evt);
            }
        });

        jRBCredito.setText("Pagamento Cartão Crédito");
        jRBCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBCreditoMouseClicked(evt);
            }
        });

        jRBDebito.setText("Pagamento Cartão Débito");
        jRBDebito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBDebitoMouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel32.setText("Valor Pago em Dinheiro");

        inputPgtoDin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputPgtoDinKeyPressed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel33.setText("Total a Pagar");

        txtTotalPgto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtTotalPgto.setText("R$ 0,00");

        jLabel35.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel35.setText("Troco");

        txtTrocoPgto.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtTrocoPgto.setText("R$ 0,00");

        jLabel39.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel39.setText("Parcelas");

        jSpinnerPgtoCartao.setModel(new javax.swing.SpinnerNumberModel(1, 1, 18, 1));
        jSpinnerPgtoCartao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerPgtoCartaoStateChanged(evt);
            }
        });

        btnCancelarPgto.setText("CANCELAR");
        btnCancelarPgto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarPgtoMouseClicked(evt);
            }
        });

        btnConfirmarPgto.setText("CONFIRMAR");
        btnConfirmarPgto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarPgtoMouseClicked(evt);
            }
        });

        txtParcela.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtParcela.setText("R$ 0,00");

        jLabel41.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel41.setText("Total por Parcela");

        javax.swing.GroupLayout jPanelPagamentoLayout = new javax.swing.GroupLayout(jPanelPagamento);
        jPanelPagamento.setLayout(jPanelPagamentoLayout);
        jPanelPagamentoLayout.setHorizontalGroup(
            jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                                .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                                .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBDinheiro)
                                    .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                                        .addComponent(jRBCredito)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRBDebito))
                                    .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(34, 34, 34)
                                        .addComponent(inputPgtoDin, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                                        .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                                                .addComponent(jLabel39)
                                                .addGap(152, 152, 152))
                                            .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                                                .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(57, 57, 57)))
                                        .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTrocoPgto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                                                .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtParcela)
                                                    .addComponent(jSpinnerPgtoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtTotalPgto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(54, 54, 54)))
                        .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelarPgto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirmarPgto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelPagamentoLayout.setVerticalGroup(
            jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(75, 75, 75)
                .addComponent(jRBDinheiro)
                .addGap(18, 18, 18)
                .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPgtoDin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBCredito)
                    .addComponent(jRBDebito))
                .addGap(18, 18, 18)
                .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerPgtoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnConfirmarPgto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnCancelarPgto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPagamentoLayout.createSequentialGroup()
                        .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txtTotalPgto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(txtTrocoPgto))))
                .addGap(36, 36, 36))
        );

        painel_base.add(jPanelPagamento, "card7");

        getContentPane().add(painel_base, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 690, 560));

        painel_lateral.setBackground(new java.awt.Color(255, 255, 255));
        painel_lateral.setLayout(null);

        btnEstoque.setText("Estoque");
        painel_lateral.add(btnEstoque);
        btnEstoque.setBounds(0, 224, 110, 112);

        btnVenda.setText("Venda");
        btnVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVendaMouseClicked(evt);
            }
        });
        painel_lateral.add(btnVenda);
        btnVenda.setBounds(0, 0, 110, 112);

        btnRetirada.setText("Retirada");
        painel_lateral.add(btnRetirada);
        btnRetirada.setBounds(0, 112, 110, 112);

        btnRelatorios.setText("Relatorios");
        painel_lateral.add(btnRelatorios);
        btnRelatorios.setBounds(0, 336, 110, 112);

        btnAdmin.setText("Admin");
        painel_lateral.add(btnAdmin);
        btnAdmin.setBounds(0, 448, 110, 112);

        getContentPane().add(painel_lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaMouseClicked
        
        this.controladora.setTimerDataHora(jLabel36, jLabel37);
        
        String cod_validar = JOptionPane.showInputDialog("DIGITE O CÓDIGO DE FUNCIONÁRIO PARA VALIDAR A OPERAÇÃO!");
        
        if(cod_validar != null && controladora.validarFuncionario(cod_validar)){
            
            painel_base.removeAll();
            painel_base.add(jPanelMenuVenda);
            painel_base.repaint();
            painel_base.revalidate();
        }    
        else{
            JOptionPane.showConfirmDialog(null, "Código Inválido! Tente Novamente.", "Validar Acesso Funcionário", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVendaMouseClicked

    private void btnRealizarVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarVendaMouseClicked
        painel_base.removeAll();
        painel_base.add(jPanelVenda);
        painel_base.repaint();
        painel_base.revalidate();
        
        controladora.setOperacao("Venda");
        
        txtCodVendedor.setText(controladora.getFuncionario().getCod_acesso());
        txtNomeVendedor.setText("%s - %s - %s".formatted(
                                        controladora.getFuncionario().getNome(),
                                        controladora.getFuncionario().getFuncao().getNome(),
                                        controladora.getFuncionario().getEmail()));
        
        controladora.configuraTabelaProdutos(jTableProdutos);        
        
        this.controladora.setTimerDataHora(jLabel5, jLabel4);
        
        txtNumVenda.setText(controladora.iniciarVenda());
        controladora.getVenda().setData_hora(controladora.getTimerDataHora(jLabel5, jLabel4));
        
    }//GEN-LAST:event_btnRealizarVendaMouseClicked

    private void btnRealizarOrçamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarOrçamentoMouseClicked
        painel_base.removeAll();
        painel_base.add(jPanelOrcamento);
        painel_base.repaint();
        painel_base.revalidate();
        this.controladora.setOperacao("Orc");
        
        //A IMPLEMENTAR
    }//GEN-LAST:event_btnRealizarOrçamentoMouseClicked

    private void btnCancelarVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarVendaMouseClicked
        controladora.cancelarVenda();
        
        JOptionPane.showConfirmDialog(null, "Cancelado com Sucesso!", "Cancelar Operação", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        painel_base.removeAll();
        painel_base.add(jPanelInicial);
        painel_base.repaint();
        painel_base.revalidate();
        limpaTelaVenda();
    }//GEN-LAST:event_btnCancelarVendaMouseClicked

    private void btnCancelarOrcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarOrcMouseClicked
        JOptionPane.showConfirmDialog(null, "Cancelado com Sucesso!", "Cancelar Operação", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        painel_base.removeAll();
        painel_base.add(jPanelInicial);
        painel_base.repaint();
        painel_base.revalidate();
        
        //A IMPLEMENTAR
    }//GEN-LAST:event_btnCancelarOrcMouseClicked

    private void btnCancelarSelecaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarSelecaoMouseClicked
       
        painel_base.removeAll();
        if(this.controladora.getOperacao().equals("Venda")){
            painel_base.add(jPanelVenda);
        }else{
            painel_base.add(jPanelOrcamento);
        }
        painel_base.repaint();
        painel_base.revalidate();
    }//GEN-LAST:event_btnCancelarSelecaoMouseClicked

    private void btnAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddItemMouseClicked
        painel_base.removeAll();
        painel_base.add(jPanelSelecaoProduto);
        painel_base.repaint();
        painel_base.revalidate();
        
        jSpinnerQtdProduto.setValue(1);
        
        controladora.popularTabelaProdutos(jTableProdutosSelecao);
        controladora.criarNovoItemVenda();
    }//GEN-LAST:event_btnAddItemMouseClicked

    private void btnAddItemOrcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddItemOrcMouseClicked
        painel_base.removeAll();
        painel_base.add(jPanelSelecaoProduto);
        painel_base.repaint();
        painel_base.revalidate();
        
        //A IMPLEMENTAR
    }//GEN-LAST:event_btnAddItemOrcMouseClicked

    private void btnConfirmarSelecaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarSelecaoMouseClicked
        
        controladora.adcionaProduto(jTableProdutosSelecao, jTableProdutos, jSpinnerQtdProduto, txtQtdItens, txtSubtotal, txtTotal, txtDesconto);
        
        painel_base.removeAll();
        if(this.controladora.getOperacao().equals("Venda")){
            painel_base.add(jPanelVenda);
        }else{
            painel_base.add(jPanelOrcamento);
        }
        painel_base.repaint();
        painel_base.revalidate();
    }//GEN-LAST:event_btnConfirmarSelecaoMouseClicked

    private void btnConfirmarVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarVendaMouseClicked

        this.controladora.finalizarSelecao(txtTotalPgto);
        controladora.setFormaPagamento("DINHEIRO");

        painel_base.removeAll();
        buttonGroup1.add(jRBDebito);
        buttonGroup1.add(jRBCredito);
        buttonGroup1.add(jRBDinheiro);
        
        jRBDinheiro.setSelected(true);
        jSpinnerPgtoCartao.setEnabled(false);
        
        painel_base.add(jPanelPagamento);
        painel_base.repaint();
        painel_base.revalidate();
    }//GEN-LAST:event_btnConfirmarVendaMouseClicked

    private void btnConfirmarPgtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarPgtoMouseClicked

        JOptionPane.showConfirmDialog(null, "Venda Concluída com Sucesso!", "Venda Concluída", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
         
        painel_base.removeAll();
        painel_base.add(jPanelInicial);
        painel_base.repaint();
        painel_base.revalidate();
        
        controladora.finalizarVenda();
        
        
    }//GEN-LAST:event_btnConfirmarPgtoMouseClicked

    private void btnCancelarPgtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarPgtoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarPgtoMouseClicked

    private void btnConfirmarOrcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarOrcMouseClicked
        // A IMPLEMENTAR
    }//GEN-LAST:event_btnConfirmarOrcMouseClicked

    private void inputNumOrcamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNumOrcamentoKeyPressed
        //A IMPLEMENTAR
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            System.out.println(inputNumOrcamento.getText());
            // na controladora: pegar o numero do orçamento e procurar os dados do orcamento, como cliente
            // vendedor, e lista de produtos do orçamento caso o orçamento seja válido, caso contrario
            // informar que orçamento é invalido. caso seja orcamento valido, preencher nome do cliente, 
            // cpf do cliente, nome e codigo do vendedor
        }
        else if(evt.getKeyCode() == KeyEvent.VK_DELETE){
            inputNumOrcamento.setText("");
        }
    }//GEN-LAST:event_inputNumOrcamentoKeyPressed

    private void inputCPFClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCPFClienteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            controladora.getVendaProduto().getVenda().setCli(controladora.buscaCliente(inputCPFCliente.getText().toString()));
            
            txtNomeCliente.setText(controladora.getVendaProduto().getVenda().getCli().getNome());
        }
        else if(evt.getKeyCode() == KeyEvent.VK_DELETE){
            inputCPFCliente.setText("");
        }
    }//GEN-LAST:event_inputCPFClienteKeyPressed

    private void jRBCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBCreditoMouseClicked
        inputPgtoDin.setEnabled(false);
        jSpinnerPgtoCartao.setEnabled(true);
        
        controladora.setFormaPagamento("CREDITO");
        
        
        txtTrocoPgto.setText("R$ %s".formatted(new DecimalFormat("0.00").format(0.0)));
        double val2 = Double.valueOf(txtTotalPgto.getText().split(" ")[1].replace(",", "."));
        txtParcela.setText("R$ %s".formatted(new DecimalFormat("0.00").format(val2/(int) jSpinnerPgtoCartao.getValue())));
    }//GEN-LAST:event_jRBCreditoMouseClicked

    private void jRBDebitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBDebitoMouseClicked
        inputPgtoDin.setEnabled(false);
        jSpinnerPgtoCartao.setEnabled(false);
        jSpinnerPgtoCartao.setValue(1);
        
        controladora.setFormaPagamento("DEBITO");
        
        txtTrocoPgto.setText("R$ %s".formatted(new DecimalFormat("0.00").format(0.0)));
        double val2 = Double.valueOf(txtTotalPgto.getText().split(" ")[1].replace(",", "."));
        txtParcela.setText("R$ %s".formatted(new DecimalFormat("0.00").format(val2)));
    }//GEN-LAST:event_jRBDebitoMouseClicked

    private void jRBDinheiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBDinheiroMouseClicked
        inputPgtoDin.setEnabled(true);
        jSpinnerPgtoCartao.setEnabled(false);
        
        controladora.setFormaPagamento("DINHEIRO");
        
    }//GEN-LAST:event_jRBDinheiroMouseClicked

    private void inputPgtoDinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPgtoDinKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            double val1 = Double.valueOf(inputPgtoDin.getText());
            double val2 = Double.valueOf(txtTotalPgto.getText().split(" ")[1].replace(",", "."));
            String form = "R$ %s".formatted(new DecimalFormat("0.00").format(val1 - val2));
                   
            txtTrocoPgto.setText(form);
        }
        else if(evt.getKeyCode() == KeyEvent.VK_DELETE){
            inputPgtoDin.setText("");
        }
    }//GEN-LAST:event_inputPgtoDinKeyPressed

    private void jSpinnerPgtoCartaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerPgtoCartaoStateChanged
        double val2 = Double.valueOf(txtTotalPgto.getText().split(" ")[1].replace(",", "."));
        txtParcela.setText("R$ %s".formatted(new DecimalFormat("0.00").format(val2/(int) jSpinnerPgtoCartao.getValue())));
    }//GEN-LAST:event_jSpinnerPgtoCartaoStateChanged

    
    
    
    
    
    public void limpaTelaVenda(){
        txtNumVenda.setText("");
        txtNomeCliente.setText("INSIRA O CPF DO CLIENTE");
        txtNomeVendedor.setText("");
        txtCodVendedor.setText("");
        inputCPFCliente.setText("");
        inputNumOrcamento.setText("");
        txtQtdItens.setText("000");
        txtSubtotal.setText("R$ 0,00");
        txtDesconto.setText("R$ 0,00");
        txtTotal.setText("R$ 0,00");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnAddItemOrc;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnCancelarOrc;
    private javax.swing.JButton btnCancelarPgto;
    private javax.swing.JButton btnCancelarSelecao;
    private javax.swing.JButton btnCancelarVenda;
    private javax.swing.JButton btnConfirmarOrc;
    private javax.swing.JButton btnConfirmarPgto;
    private javax.swing.JButton btnConfirmarSelecao;
    private javax.swing.JButton btnConfirmarVenda;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnRealizarOrçamento;
    private javax.swing.JButton btnRealizarVenda;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnRetirada;
    private javax.swing.JButton btnVenda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField inputCPFCliente;
    private javax.swing.JTextField inputCPFClienteOrc;
    private javax.swing.JTextField inputNumOrcamento;
    private javax.swing.JTextField inputPgtoDin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelInicial;
    private javax.swing.JPanel jPanelMenuVenda;
    private javax.swing.JPanel jPanelOrcamento;
    private javax.swing.JPanel jPanelPagamento;
    private javax.swing.JPanel jPanelSelecaoProduto;
    private javax.swing.JPanel jPanelVenda;
    private javax.swing.JRadioButton jRBCredito;
    private javax.swing.JRadioButton jRBDebito;
    private javax.swing.JRadioButton jRBDinheiro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner jSpinnerPgtoCartao;
    private javax.swing.JSpinner jSpinnerQtdProduto;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTable jTableProdutosOrc;
    private javax.swing.JTable jTableProdutosSelecao;
    private javax.swing.JPanel painel_base;
    private javax.swing.JPanel painel_lateral;
    private javax.swing.JLabel txtCodVendOrc;
    private javax.swing.JLabel txtCodVendedor;
    private javax.swing.JLabel txtDesconto;
    private javax.swing.JLabel txtDescontoOrc;
    private javax.swing.JLabel txtNomeCliente;
    private javax.swing.JLabel txtNomeClienteOrc;
    private javax.swing.JLabel txtNomeVendOrc;
    private javax.swing.JLabel txtNomeVendedor;
    private javax.swing.JLabel txtNumOrc;
    private javax.swing.JLabel txtNumVenda;
    private javax.swing.JLabel txtParcela;
    private javax.swing.JLabel txtQtdItens;
    private javax.swing.JLabel txtQtdItensOrc;
    private javax.swing.JLabel txtSubtotal;
    private javax.swing.JLabel txtSubtotalOrc;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtTotalOrc;
    private javax.swing.JLabel txtTotalPgto;
    private javax.swing.JLabel txtTrocoPgto;
    // End of variables declaration//GEN-END:variables
}
